generic_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('posts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . import views
from .views import (PostCreateView, PostListView,
                    PostDetailView, PostUpdateView,
                    PostDeleteView, comment_delete)

urlpatterns = [
    path('', views.PostListView.as_view(), name="post_list"),
    path('search/', views.SearchResultView.as_view(), name="post_search"),
    path('posts/<slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path('create-post/', views.PostCreateView.as_view(), name="post_create"),
    path('<slug>/update-post/', views.PostUpdateView.as_view(), name="post_update"),
    path('<slug>/delete-post/', views.PostDeleteView.as_view(), name="post_delete"),
    path('<id>/delete-comment/',
         views.comment_delete, name="comment_delete"),
    path('like/<slug>', views.like_it, name="post_like"),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
import uuid


class Post(models.Model):
    """ Post has a many-to-one relationship with its respective User"""
    title = models.CharField(max_length=100)
    body = models.TextField()
    published_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(
        editable=False, max_length=100, unique=True, null=False)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.title} by {self.author.username}'

    def save(self, *args, **kwargs):
        if not self.slug:
            post_title = self.title
            slug = slugify(post_title, allow_unicode=True)
            self.slug = slug + '-' + str(uuid.uuid4())
        super().save(*args, **kwargs)

    @property
    def likes_count(self):
        return self.like_set.all().count()

    @property
    def comments_count(self):
        return self.comment_set.all().count()

    @property
    def views_count(self):
        return self.visualization_set.all().count()


class Comment(models.Model):
    """ Comment has a many-to-one relationship with both User and Post """
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField()
    published_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author.username}'s comment"


class Like(models.Model):
    """ Like has a many-to-one relationship with both User and Post """
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author.username} liked it'


class Visualization(models.Model):
    """ Visualization has a many-to-one relationship with both User and Post """
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author.username} viewed it'

posts/forms.py
from django import forms
from .models import Post, Comment
from django.utils.text import slugify
from django.core.exceptions import ValidationError


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from .models import Post, Comment, Like, Visualization
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .forms import PostForm, CommentForm
from django.http import JsonResponse, Http404
from django.db.models import Q


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('post_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'post_action': 'create'
        })
        return context


class PostListView(ListView):
    model = Post
    paginate_by = 5
    context_object_name = 'posts'
    ordering = ['-published_at']


class PostDetailView(DetailView,  MultipleObjectMixin):
    model = Post
    paginate_by = 3

    def get_object(self, **kwargs):
        object = super().get_object(**kwargs)
        if self.request.user.is_authenticated:
            Visualization.objects.get_or_create(
                author=self.request.user, post=object)
        return object

    # def post(self, *args, **kwargs):
    #     form = CommentForm(self.request.POST)
    #     if form.is_valid() and form.has_changed():
    #         comment = form.instance
    #         comment.post = self.get_object()
    #         comment.author = self.request.user
    #         comment.save()
    #         return redirect('post_detail', slug=self.get_object().slug)
    #     return redirect('post_detail', slug=self.get_object().slug)

    def post(self, *args, **kwargs):
        if self.request.is_ajax():
            data = {}

            form = CommentForm(self.request.POST)
            if form.is_valid() and form.has_changed():
                comment = form.instance
                comment.post = self.get_object()
                comment.author = self.request.user
                comment.save()
                data['body'] = comment.body
                data['id'] = comment.pk

            data['success'] = True
            return JsonResponse(data)
        else:
            raise Http404

    def get_context_data(self, **kwargs):
        object_list = Comment.objects.filter(
            post=self.get_object()).order_by('-published_at')
        context = super().get_context_data(object_list=object_list, **kwargs)
        context.update({
            'form': CommentForm()
        })
        return context


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
   # success_url = reverse_lazy('post_detail')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'post_action': 'update'
        })
        return context

    def test_func(self):
        post = self.get_object()
        if post.author == self.request.user:
            return True
        return False

    def get_success_url(self):
        post_slug = self.kwargs['slug']
        return reverse_lazy('post_detail', kwargs={'slug': post_slug})


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')
    success_message = "Post deleted successfully."

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)

    def test_func(self):
        post = self.get_object()
        if post.author == self.request.user:
            return True
        return False


class SearchResultView(ListView):
    model = Post
    context_object_name = 'posts'

    def get_queryset(self):
        query = self.request.GET.get('search_string')
        return Post.objects.filter(
            Q(title__icontains=query) | Q(body__icontains=query)
        ).order_by("-published_at")


@login_required
def like_it(request, slug):
    if request.is_ajax():
        post = get_object_or_404(Post, slug=slug)

        try:
            newCount = post.likes_count - 1
            like = Like.objects.get(author=request.user, post=post)
            like.delete()
            return JsonResponse({'newCount': newCount})

        except Like.DoesNotExist:
            Like.objects.create(author=request.user, post=post)
            return JsonResponse({'newCount': post.likes_count})
    else:
        raise Http404


@login_required
def comment_delete(request, id):
    if request.is_ajax():
        try:
            comment = Comment.objects.get(id=id)
            post = Post.objects.get(pk=comment.post.pk)
            if request.user == comment.author:
                comment.delete()
                return JsonResponse({'isDeleted': True, 'commCount': post.comments_count})
            else:
                return JsonResponse({'isDeleted': False, })
        except Comment.DoesNotExist:
            raise Http404
    else:
        raise Http404

templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>DjangoBlog {% block title %}{% endblock %}</title>
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
   <!-- Compiled and minified CSS -->
</head>
<body>
  <header>
    <nav class="mbtm-nav nav-extension">
      <div class="nav-wrapper teal lighten-1">
        <div class="container">
          <a href="{% url 'post_list' %}" class="brand-logo">Blog</a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'post_list' %}">Blog</a></li>
            {% comment %} <li><a href="#">About</a></li> {% endcomment %}
            {% if user.is_authenticated %}
              <li><a href="{% url 'profile' %}">Profile</a></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'login' %}">Login</a></li>
              <li><a href="{% url 'register' %}">Signup</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <ul class="sidenav collapsible" id="mobile-demo">
      <li><a href="{% url 'post_list' %}">Blog<i class="material-icons left">view_headline</i></a></li>
      {% comment %} <li><a href="#">About<i class="material-icons left">help_outline</i></a></li> {% endcomment %}
      {% if user.is_authenticated %}
        <li><a href="{% url 'profile' %}">Profile<i class="material-icons left">portrait</i></a></li>
        <li><a href="{% url 'logout' %}">Logout<i class="material-icons left">highlight_off</i></a></li>
      {% else %}
        <li><a href="{% url 'login' %}">Login<i class="material-icons left">person</i></a></li>
        <li><a href="{% url 'register' %}">SignUp<i class="material-icons left">person_add</i></a></li>
      {% endif %}
    </ul>
  </header>

  <main class="container">
    <div class="row">
      <div class="col s12 m8">
        <div class="materialert danger center-align ">
              <i class="material-icons">warning</i><br>
            <p>This blog is for testing purposes. <strong><b> Expect data loss!</b></strong></p>         
          </div>
        {% if form.errors %}
          {% for field in form %}
              {% for error in field.errors %}
                <div class="materialert danger">
                    <i class="material-icons">error_outline</i>
                    {{ error|escape }}
                </div>
              {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
              <div class="materialert danger">
                  <i class="material-icons">error_outline</i>
                  {{ error|escape }}
              </div>
          {% endfor %}
        {% endif %}

        {% if messages %}
          {% for message in messages %}
            {% if message.tags %}
              <div class="materialert {{ message.tags }} z-depth-3">
                <i class="material-icons">info_outline</i>
                {{ message }}
              </div>
            {% endif %}
          {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
      </div>
      <div class="col m4 hide-on-small-only center-align valign-wrapper">
      </div>
    </div>
  </main>

  <script src="{% static 'js/jquery-2.1.1.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/materialize.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/app.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/infinite.min.js' %}" type="text/javascript"></script>
  {% block custom_js %}
  {% endblock %}
  </body>
</html>

templates/posts/post_confirm_delete.html
{% extends 'posts/base.html' %}

{% block content %}
    <div class="card z-depth-2">
        <div class="card-content center-align">
            <i class="orange-text medium material-icons">report</i>
            <form method="POST">
                {% csrf_token %}
                <h5 class="grey-text">Are you sure you would like to delete this post?</h5>
                <br>
                <a href="{% url 'post_detail' post.slug %}" class="btn blue">Cancel</a>
                <button type="submit" class="btn orange">Delete</button>
            </form>

        </div>
    </div>
{% endblock %}

templates/posts/post_detail.html
{% extends 'posts/base.html' %}
{% load static %}
{% load materializecss %}

{% block content %}
    <div class="card z-depth-2">
        <div class="card-content">
          <span style="margin-bottom: 0px" class="card-title teal-text">{{ post.title|title }}</span>
          <small class="grey-text">By {{ post.author.username }} about {{ post.published_at|timesince }} ago</small>
          <br><br>
            {{ post.body|linebreaks}}
        </div>
        <div class="card-action">
          <span class="hide-on-small-only orange-text right"> {{ post.views_count }} </span><i style="margin-right: 1%" class="hide-on-small-only teal-text right material-icons">visibility</i>
          <a class="likebtn"  data-url="{% url 'post_like' post.slug %}" likes-count="{{ post.likes_count }}"><span class="right"> {{ post.likes_count }} </span><i style="margin-right: 1%" class="teal-text right material-icons">thumb_up</i></a>
          {% if post.author == user %}
            <a href="{% url 'post_update' post.slug %}" class="left">Update</a>
            <a href="{% url 'post_delete' post.slug %}" class="red-text left">Delete</a>
          {% endif %}
          <a href="{% url 'post_list' %}" class="hide-on-med-and-down teal-text left">Go Back</a>
        </div>
    </div>
  <br><br>

{% if user.is_authenticated %}
  <form method="POST" id="comment-form" action-url="{% url "post_detail" post.slug %}">
    <div class="row">
      <div class="col s12">
        {% csrf_token %}
          {{ form.body | materializecss }}
      </div>
      <div class="col s12">
        <button type="submit" class="right btn waves-effect waves-light teal">Comment</button>
    </div>
    </div>
  </form>
{% else %}
<div>
   <input disabled value="Login to comment..." id="disabled" type="text" class="validate"><p></p>
  <a href="{% url  'login' %}?next={{ request.path }}" class="right btn waves-effect waves-light teal">Login</a>
</div>
{% endif %}
         
  <br><br>
  <h5  class="center-align teal-text"><span id="commentsCount">{{ post.comments_count }}</span> Comment(s)</h5>
  <div id="posts"></div>
  {% if object_list %}
   <div class="infinite-container">
      {% for comment  in object_list %}
      <div class="card infinite-item z-depth-2">
        <div class="card-content row ">
            {% if request.user == comment.author %}
              <a href="" class="deleteComm" delete-url="{% url 'comment_delete' comment.id %}"><i class="material-icons pink-text   lighten-4 right">delete</i></a>
            {% endif %}
            <div class="col s12 m4 center-align">
              <img width="50" height="50" src="{% static "imgs/default.jpg" %}" alt="profile-picture" class=" circle">
              <br>{{ comment.author.username }}<br><br>
            </div>
              <div class="col s12 m8" style="word-wrap: break-word">
              {% if comment.body|length > 150 %}
                {{ comment.body| slice:":150" | linebreaksbr }}<span class="dots">...<br></span><span class="more" style="display: none">{{ comment.body| slice:"15:" | linebreaksbr }}</span>
                <a class="read orange-text">Read More</a>
              {% else %}
                {{ comment.body | linebreaksbr }}
              {% endif %}
                <br><br><small>{{ comment.published_at| timesince }} ago</small>
              </div>
            </div>
          
        </div>
      {% endfor %}
    </div>

 <div class="loading" style="display: none;">
    <br>
      <div class="progress">
        <div class="indeterminate"></div>
      </div>
    <br>
    </div>

    {% if page_obj.has_next %}
      <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
    {% endif %}

  {% endif %}
      
{% endblock %}

{% block custom_js %}
<script>

 var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
      onBeforePageLoad: function () {
        $('.loading').show();
      },
      onAfterPageLoad: function ($items) {
        $('.loading').hide();
      },
    });

$(document).on("click", '.read', function(e) {
  $(this).prev().fadeToggle('fast', 'linear');
   var text = $(this).text();
   if (text == "Read More"){
     var obj = $(this).text('\nRead Less');
     obj.html(obj.html().replace(/\n/g,'<br/>'));
   }
   else {
     $(this).text('Read More');
   }
  $(this).siblings('.dots').toggle();
});

{% if user.is_authenticated %}
    $(document).on("click", '.likebtn', function(e) { 
      e.preventDefault()
      var this_ = $(this);
      var likeUrl = this_.attr('data-url');
      var likesCount = parseInt(this_.attr('likes-count'));

      $.ajax({
        url: likeUrl, 
        method: 'GET',
        data: {},
        success: function(data){
          this_.find('span').text(data.newCount);
        }
      }); 
    });

    $(document).on("click", '.deleteComm', function(e) { 
      e.preventDefault()
      var this_comm = $(this);
      var commUrl = this_comm.attr('delete-url');

      $.ajax({
        url: commUrl, 
        method: 'GET',
        data: {},
        success: function(data){
          if (data.isDeleted){
            this_comm.closest('.card').remove();
            $('#commentsCount').text(data.commCount); 
          }
          else {
            alert('Unable to delete comment');
          }
        }
      }); 
    });

    $(document).on('submit', '#comment-form', function(e){
      e.preventDefault()
        var this_ = $(this)
        if(!($('#comment-form').find('#id_body').val().trim())){
             return;           
        }
        var  actUrl = this_.attr('action-url');
        $.ajax({
          type:'POST',
          dataType:'json', 
          url: actUrl,
          data:{
              body:$('#id_body').val(),
              csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
              action: 'POST',
          },
    
       
        
          success:function(json){
            
              document.getElementById("comment-form").reset();
              $("#posts").prepend(
                '<div class="card  z-depth-2">' +
                    '<div class="card-content row ">' +
                        '<a href="" class="deleteComm" delete-url="/' + json.id + '/delete-comment/"><i class="material-icons pink-text   lighten-4 right">delete</i></a>' +
                        '<div class="col s12 m4 center-align">' +
                          '<img width="50" height="50" src="{% static "imgs/default.jpg" %}" alt="profile-picture" class=" circle">' +
                          '<br> {{request.user.username }}<br>'  +
                        '</div>' +
                          '<div style="word-wrap: break-word" class="col s12 m8">' + '' + 
                            '<span> ' +  json.body.replace( /\n/g, '<br \\>' )  + '</span>' +
                        '<br><br><small>0 minutes ago</small>' + 
                        ' </div>' +
                      '</div>'  +
                    '</div>'
              );
              
              var commentCount = parseInt($('#commentsCount').text()) + 1;
              $('#commentsCount').text(commentCount);

           }
      });
});


  {% endif %}

</script>
{% endblock %}

templates/posts/post_form.html
{% extends 'posts/base.html' %}
{% load materializecss %}

{% block content %}
<div class="card z-depth-2">
    <div class="card-content">
        <h4 class="center-align grey-text lighten-1">{{ post_action | title }} Post</h4>
        <form method="POST">
            {% csrf_token %}
            {{ form|materializecss }}
                <button class="btn waves-effect z-depth-1 mtop" type="submit" name="action">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/post_list.html
{% extends 'posts/base.html' %}

{% block content %}
    {% if posts %}
         <form  action="{% url "post_search" %}" method="GET">
           <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">search</i>
                <input name="search_string" type="text" id="search_string">
                <label for="search_string">Search Posts</label>
              </div>
            </div>
        </form> 
        <div class="infinite-container">
          {% for post in posts %}
              <div class="infinite-item">
                <div class="card z-depth-2">
                    <div class="card-content">
                      <a href="{% url 'post_detail' post.slug %}" class="orange-text"><span class="card-title">{{ post.title|title }}</span></a>
                      <p>{{ post.body|linebreaks|truncatechars:150}}
                        {% if post.body|length > 150 %}
                            <a href="{% url 'post_detail' post.slug %}" class="orange-text">Read More</a>
                        {% endif %}
                      </p>
                    </div>
                    <div class="card-action">
                      <small class="grey-text lighten-1">{{ post.author.username }} {{ post.published_at|date:"M d, Y" }}</small>
                      <span class="orange-text right"> {{ post.comments_count }} </span><i style="margin-right: 1%" class="teal-text right material-icons">comment</i>
                      <span class="hide-on-small-only orange-text right"> {{ post.views_count }} </span><i style="margin-right: 1%" class="hide-on-small-only teal-text right material-icons">visibility</i>
                      <a class="likebtn"  data-url="{% url 'post_like' post.slug %}" likes-count="{{ post.likes_count }}"><span class="right"> {{ post.likes_count }} </span><i style="margin-right: 1%" class="teal-text right material-icons">thumb_up</i></a>
                    </div>
                  </div>
              </div>
            {% endfor %}
          </div>

    <div class="loading" style="display: none;">
    <br>
      <div class="progress">
        <div class="indeterminate"></div>
      </div>
    <br>
    </div>


    {% if page_obj.has_next %}
      <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
    {% endif %}

    {% else %}
        <div class="card z-depth-2">
            <div class="card-content center-align">
                <i class="grey-text lighten-1 medium material-icons">folder_open</i>
                <h4 class="grey-text lighten-1 mtzero">No Posts Found...</h4>
                {% comment %} <small class="grey-text lighten-2"><a class="orange-text" href="{{ request.scheme }}://{{ request.get_host }}{% url 'post_create' %}">Be the first!</a></small> {% endcomment %}
            </div>
        </div>
    {% endif %}
    {% if user.is_authenticated %}
      <div class="fixed-action-btn">
        <a href="{% url 'post_create' %}" class="btn-floating btn-large">
          <i class="large material-icons teal lighten-1">add</i>
        </a>
      </div>
    {% endif %}
{% endblock %}

{% block custom_js %}
<script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
      onBeforePageLoad: function () {
        $('.loading').show();
      },
      onAfterPageLoad: function ($items) {
        $('.loading').hide();
      }
    });

{% if user.is_authenticated %}
    $(document).on("click", '.likebtn', function(e) { 
      e.preventDefault()
      var this_ = $(this);
      var likeUrl = this_.attr('data-url');
      var likesCount = parseInt(this_.attr('likes-count'));

      $.ajax({
        url: likeUrl, 
        method: 'GET',
        data: {},
        success: function(data){
          this_.find('span').text(data.newCount);
     
        }
        /*error: function(error){
          console.log(error);
          console.log("error");
        }*/
      }); 
    });
  {% endif %}


   {% comment %} $(document).on("click", 'i', function(event) { 
    $(this).removeClass('teal-text');
  }); {% endcomment %}
  
</script>
{% endblock %}
 